### ISSUE TITLE
Error "parseRaw expects an array"

### ISSUE THREAD

**Issue by stefahn** [vanilla/garden-cli#21]
I am trying to run https://github.com/bramus/mixed-content-scan. When I enter the command I get the following error message:

> user:/home/www/user > files/swm2/composer/.composer/vendor/bin/mixed-content-scan https://example.com
> Content-type: text/html; charset=UTF-8
> <br />
> <b>Fatal error</b>:  Uncaught Exception: Garden\Cli\Cli::parseRaw expects an array in /files/swm2/composer/.composer/vendor/bramus/mixed-content-scan/vendor/vanilla/garden-cli/src/Cli.php:385
> Stack trace:
> #0 /files/swm2/composer/.composer/vendor/bramus/mixed-content-scan/vendor/vanilla/garden-cli/src/Cli.php(338): Garden\Cli\Cli-&gt;parseRaw(NULL)
> #1 /files/swm2/composer/.composer/vendor/bramus/mixed-content-scan/bin/mixed-content-scan(40): Garden\Cli\Cli-&gt;parse(NULL, true)
> #2 {main}
> thrown in <b>/files/swm2/composer/.composer/vendor/bramus/mixed-content-scan/vendor/vanilla/garden-cli/src/Cli.php</b> on line <b>385</b><br />

This error is thrown with both garden-cli version 1.6.3 and 2.0.
Using PHP 7.1.9 (cgi-fcgi).

How to fix this?

**Comment by Charrondev** [comment]
The issue is that you're passing in null arguments. Arguments should always be an array with the first one being the command that was run. That doesn't seem to always work out so here's an example of how we guarded against it in `vanilla-cli` https://github.com/vanilla/vanilla-cli/blob/d8f89d8d68c4a4c84610139b41280779e7390f6e/src/Vanilla/Cli/Cli.php#L66

**Comment by stefahn** [comment]
I don't really get it. Can you tell me what I need to write on the command line instead of `file url`?
Thanks for any help.

**Comment by charrondev** [comment]
What `file url` are you referring to exactly? Garden CLI is a library for building command tools. If you are having an issue with `mixed-content-scan` you should file an issue on that repo instead. I had assumed you were the author of that tool, in which case it is passing null as an argument, when Garden CLI requires an array. In short, the issue is `mixed-content-scan` not `garden-cli`.

**Comment by stefahn** [comment]
Thanks.

I found out how to run the tool. For some reason I had to add `php_cli` in front of the command.
